### PR TITLE
Fixing github actions

### PR DESCRIPTION
**Pull request by volivers**
## Description

Updated Deploy Production workflow, given the previous failed tests. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by apuntovanini** [comment]
I don't know how apuntovanini merges this automatically, I didn't do it! 😄 
maybe @mkostrikin can help me out with this

**Comment by volivers** [comment]
That's odd @apuntovanini. I really though you did it!
Either way, the workflow is still breaking on this action:

Captura de ecrã 2021-04-22, às 12 12 23

Node's version seems to be fine on the package.json though.

**Comment by apuntovanini** [comment]
From the action readme I see "The action will first check the local cache for a semver match. The hosted images have been updated with the latest of each LTS from v8, v10, v12, and v14" (https://github.com/actions/setup-node#v2)

We may need to downgrade to 14 then...
Let me try pushing to this branch

**Comment by apuntovanini** [comment]
https://github.com/uidu-org/guidu/pull/77

**Comment by mkostrikin** [comment]
That was fast.

**Pull request merged**
